package dev.pti.common.events;

import com.github.f4b6a3.ulid.UlidCreator;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * A UI event as a producer hands it to {@link UiEventPublisher} (DOC-33 §2.1). The Kafka envelope is built from it
 * by the publisher's adapter: snake_case envelope fields, lowercase channel, and {@code data} in camelCase exactly as
 * given here, because the API forwards it to SSE without renaming keys.
 *
 * <p>The record is plain Java: {@code data} holds JSON-compatible values (strings, numbers, booleans, {@code null},
 * {@link Instant}, {@link java.util.UUID}, and nested maps and collections of those) and the adapter chooses how to
 * write them.
 *
 * @param id ULID, generated by {@link #of}
 * @param type event type such as {@code bunching.opened} (DOC-33 §3)
 * @param channel the channel a client subscribes to
 * @param audience who may see the event; used for filtering and never sent to clients
 * @param occurredAt wall clock time the event was created (not business time)
 * @param sourceRecordTs the record time of the data that caused the event, for the end-to-end latency metric;
 *     {@code null} for events from ticks, jobs and recomputes (DR-57)
 * @param routeId route the event is about, when it is about one
 * @param key Kafka key (DOC-33 §3), which keeps the events of one entity in one partition
 * @param data the payload; at most {@value #MAX_DATA_BYTES} bytes once written as JSON
 */
public record UiEvent(
        String id,
        String type,
        UiChannel channel,
        Audience audience,
        Instant occurredAt,
        @Nullable Instant sourceRecordTs,
        @Nullable String routeId,
        String key,
        Map<String, Object> data) {

    /** The largest {@code data} a publisher may send (DOC-33 §2.1); {@code vehicles.batch} needs about 15 KiB. */
    public static final int MAX_DATA_BYTES = 64 * 1024;

    private static final int MAX_DEPTH = 32;

    /**
     * @throws IllegalArgumentException when a text field is blank or {@code data} is larger than
     *     {@value #MAX_DATA_BYTES} bytes. That is a programming error, so it is not a {@code PtiException}.
     */
    public UiEvent {
        requireText(id, "id");
        requireText(type, "type");
        requireText(key, "key");
        if (channel == null || audience == null || occurredAt == null || data == null) {
            throw new IllegalArgumentException("channel, audience, occurredAt and data are required");
        }
        data = Collections.unmodifiableMap(new LinkedHashMap<>(data));
        int bytes = estimatedJsonBytes(data, 0);
        if (bytes > MAX_DATA_BYTES) {
            throw new IllegalArgumentException(
                    "UI event data of type " + type + " is about " + bytes + " bytes, the limit is " + MAX_DATA_BYTES);
        }
    }

    /**
     * A new event with a fresh monotonic ULID as id. {@code occurredAt} is the wall clock, so callers with a
     * {@code BusinessClock} pass {@code clock.realNow()}.
     */
    public static UiEvent of(
            Instant occurredAt,
            String type,
            UiChannel channel,
            Audience audience,
            String key,
            @Nullable String routeId,
            @Nullable Instant sourceRecordTs,
            Map<String, Object> data) {
        return new UiEvent(
                UlidCreator.getMonotonicUlid().toString(),
                type,
                channel,
                audience,
                occurredAt,
                sourceRecordTs,
                routeId,
                key,
                data);
    }

    private static void requireText(@Nullable String value, String name) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(name + " must not be blank");
        }
    }

    /**
     * An estimate of the size of {@code value} as compact JSON, in bytes. Good to a few percent, which is enough for
     * a limit that only guards against programming errors, and needs no JSON library here.
     */
    private static int estimatedJsonBytes(@Nullable Object value, int depth) {
        if (depth > MAX_DEPTH) {
            throw new IllegalArgumentException("UI event data is nested deeper than " + MAX_DEPTH);
        }
        if (value == null) {
            return 4;
        }
        if (value instanceof Map<?, ?> map) {
            int bytes = 2;
            for (Map.Entry<?, ?> entry : map.entrySet()) {
                bytes += estimatedJsonBytes(String.valueOf(entry.getKey()), depth + 1)
                        + 1
                        + estimatedJsonBytes(entry.getValue(), depth + 1)
                        + 1;
            }
            return bytes;
        }
        if (value instanceof Collection<?> collection) {
            int bytes = 2;
            for (Object element : collection) {
                bytes += estimatedJsonBytes(element, depth + 1) + 1;
            }
            return bytes;
        }
        if (value instanceof Number || value instanceof Boolean) {
            return value.toString().length();
        }
        // Strings and anything written as a string (Instant, UUID, enums): quotes plus escapes.
        String text = value.toString();
        int bytes = 2 + text.getBytes(StandardCharsets.UTF_8).length;
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (c == '"' || c == '\\' || c < 0x20) {
                bytes++;
            }
        }
        return bytes;
    }
}
